<a href="https://colab.research.google.com/github/ManelSoengas/DL_Task1/blob/main/DL_Bert_11_8_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Swapping + ampliar la profundidad red.



In [ ]:
# Cargar las librerias y recursos necesarios.

import pandas as pd
from sklearn.model_selection import train_test_split
!pip install transformers
from transformers import BertTokenizer, TFBertForSequenceClassification

#transformers
from transformers import BertTokenizerFast
from transformers import TFBertModel
from transformers import RobertaTokenizerFast
from transformers import TFRobertaModel

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 61.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 24.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 86.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 81.6 MB/s eta 0:00:00


In [ ]:
from sklearn.utils import shuffle
# Cargar datos preprocesados
#train_data = pd.read_csv('/content/EXIST2021_training.tsv', delimiter=',', encoding='latin1')
#test_data = pd.read_csv('/content/EXIST2021_test_labeled.tsv', delimiter=',', encoding='latin1')

test_data = pd.read_csv('/content/EXIST2021_test_labeled.tsv', sep='\t')
train_data = pd.read_csv('/content/swapp_EXIST2021_training.tsv', sep='\t') #swapping data_set training
# Mezclar los datos de entrenamiento
shuffled_train_data = shuffle(train_data, random_state=42)

# Mezclar los datos de prueba
shuffled_test_data = shuffle(test_data, random_state=42)

In [ ]:
test_data.shape
train_data.shape

(11977, 7)

In [ ]:
train_data['length'] = train_data['text'].apply(len)
test_data['length'] = test_data['text'].apply(len)

In [ ]:
train_data['word_count'] = train_data['text'].apply(lambda x: len(x.split()))
test_data['word_count'] = test_data['text'].apply(lambda x: len(x.split()))

In [ ]:
train_data.head(5), test_data.head(5)

(   test_case  id   source language  \
 0  EXIST2021   1  twitter       en   
 1  EXIST2021   2  twitter       en   
 2  EXIST2021   3  twitter       en   
 3  EXIST2021   4  twitter       en   
 4  EXIST2021   5  twitter       en   
 
                                                 text       task1  \
 0  She calls herself "anti-feminazi" how about sh...      sexist   
 1  Now, back to these women, the brave and the be...  non-sexist   
 2  @CurvyBandida @Xalynne_B Wow, your skirt is ve...      sexist   
 3  @AurelieGuiboud Incredible!  Beautiful!But I l...  non-sexist   
 4  i find it extremely hard to believe that kelly...  non-sexist   
 
                     task2  length  word_count  
 0  ideological-inequality     186          27  
 1              non-sexist     268          47  
 2         objectification      92          16  
 3              non-sexist     157          21  
 4              non-sexist     282          53  ,
    test_case    id   source language  \
 0  EXIST202

In [ ]:
# Ordenar el DataFrame por la columna 'word_count' en orden descendente
train_data_sorted = train_data.sort_values(by='word_count', ascending=False)

# Obtener las 5 filas con el máximo número de palabras
top_5_max_word_count = train_data_sorted.head(5)

# Mostrar las 5 filas
print(top_5_max_word_count)


      test_case    id   source language  \
1099  EXIST2021  1100  twitter       en   
2611  EXIST2021  2612  twitter       en   
2635  EXIST2021  2636  twitter       en   
3027  EXIST2021  3028  twitter       en   
2829  EXIST2021  2830  twitter       en   

                                                   text       task1  \
1099  @OcculticAcid @Missy_Andry @SquawkyAtan @LMoon...      sexist   
2611  @CrossBiddy @NinjaSocialist @SR_Duncan @Shotgu...      sexist   
2635  @Holdenheim1 @shahjoffe @VampVespertilio @Elfs...      sexist   
3027  @Eleanor_Greet @aletheia327 @JaneyCavanagh @ba...  non-sexist   
2829  @brightstrangely @hwashington22 @nogenderid @h...  non-sexist   

                       task2  length  word_count  
1099  ideological-inequality     958         101  
2611         sexual-violence     962         101  
2635         objectification     915         100  
3027              non-sexist     962          99  
2829              non-sexist     961          97  


In [ ]:
# Ordenar el DataFrame por la columna 'word_count' en orden descendente
test_data_sorted = test_data.sort_values(by='word_count', ascending=False)

# Obtener las 5 filas con el máximo número de palabras
top_5_max_word_count = test_data_sorted.head(5)

# Mostrar las 5 filas
print(top_5_max_word_count)

      test_case     id source language  \
1860  EXIST2021   8838    gab       en   
9     EXIST2021   6987    gab       en   
233   EXIST2021   7211    gab       en   
2067  EXIST2021   9045    gab       en   
4296  EXIST2021  11274    gab       es   

                                                   text       task1  \
1860  Great piece of work regarding China. Thank you...      sexist   
9     Although the Christian denial isn't emphasized...  non-sexist   
233   THE DECLARATION OF KANNA =)by Loki Rikako Oryo...  non-sexist   
2067  Chapter 1: Introduction (Part 1 of 2)… sociali...  non-sexist   
4296  CLUB DE SATANICOS BILDERBERG, LOS AMOS DEL MUN...  non-sexist   

                             task2  length  word_count  
1860  misogyny-non-sexual-violence    3067         553  
9                       non-sexist    3520         537  
233                     non-sexist    3285         528  
2067                    non-sexist    3259         514  
4296                    non-sexist 

In [ ]:
# Contar cuántas filas tienen un valor mayor a 255 en la columna 'word_count'
count_above_255 = (test_data['word_count'] > 255).sum()

# Mostrar el resultado
print("Número de filas con word_count > 255:", count_above_255)


Número de filas con word_count > 255: 10


In [ ]:
import re

def anonimize_text(text):
    # Anonimizar nombres de usuario
    text = re.sub(r'@[\w_]+', '@user', text)

    # Anonimizar hashtags
    text = re.sub(r'#\w+', '#hashtag', text)

    # Anonimizar enlaces
    text = re.sub(r'https?://\S+', 'link', text)

    return text

shuffled_train_data['text_anonymized'] = shuffled_train_data['text'].apply(anonimize_text)
shuffled_test_data['text_anonymized'] = shuffled_test_data['text'].apply(anonimize_text)


In [ ]:
# Convertir a minúsculas

shuffled_train_data.text_anonymized = shuffled_train_data.text_anonymized.str.lower()
shuffled_train_data.head(10)
shuffled_test_data.text_anonymized = shuffled_test_data.text_anonymized.str.lower()
shuffled_test_data.head(10), shuffled_train_data.head(10)

(      test_case     id   source language  \
 1374  EXIST2021   8352  twitter       en   
 2293  EXIST2021   9271  twitter       es   
 3379  EXIST2021  10357  twitter       es   
 1090  EXIST2021   8068  twitter       en   
 1803  EXIST2021   8781  twitter       en   
 2694  EXIST2021   9672  twitter       es   
 461   EXIST2021   7439  twitter       en   
 3346  EXIST2021  10324  twitter       es   
 2297  EXIST2021   9275  twitter       es   
 2873  EXIST2021   9851  twitter       es   
 
                                                    text       task1  \
 1374  if i ever catch anyone beating a women, i swea...  non-sexist   
 2293  "No sé si habrá un #MeToo del cine español. Cu...  non-sexist   
 3379  En el dia de hoy se sostuvo reunión con Claudi...  non-sexist   
 1090  Man I love a good podcast. I highly recommend ...  non-sexist   
 1803  #BidenErasedWomen#BidenAintSmart#RealWomenMatt...      sexist   
 2694  tw/ transfobia "no es opresión" -hombres desle...      sexist   

In [ ]:
# Eliminar url/website que no usan http, solo utilizan .com websites
# Palabras separadas por a . no son eliminadas

shuffled_train_data.text_anonymized = shuffled_train_data.text_anonymized.apply(lambda x: re.sub(r"www\.[a-z]?\.?(com)+|[a-z]+\.(com)", '', x))
shuffled_train_data.head(10)
shuffled_test_data.text_anonymized = shuffled_test_data.text_anonymized.apply(lambda x: re.sub(r"www\.[a-z]?\.?(com)+|[a-z]+\.(com)", '', x))
shuffled_test_data.head(10)

test_case     id   source language  \
1374  EXIST2021   8352  twitter       en   
2293  EXIST2021   9271  twitter       es   
3379  EXIST2021  10357  twitter       es   
1090  EXIST2021   8068  twitter       en   
1803  EXIST2021   8781  twitter       en   
2694  EXIST2021   9672  twitter       es   
461   EXIST2021   7439  twitter       en   
3346  EXIST2021  10324  twitter       es   
2297  EXIST2021   9275  twitter       es   
2873  EXIST2021   9851  twitter       es   

                                                   text       task1  \
1374  if i ever catch anyone beating a women, i swea...  non-sexist   
2293  "No sé si habrá un #MeToo del cine español. Cu...  non-sexist   
3379  En el dia de hoy se sostuvo reunión con Claudi...  non-sexist   
1090  Man I love a good podcast. I highly recommend ...  non-sexist   
1803  #BidenErasedWomen#BidenAintSmart#RealWomenMatt...      sexist   
2694  tw/ transfobia "no es opresión" -hombres desle...      sexist   
461    @not_corona_ maybe its repressed antiblackness .  non-sexist   
3346  @dara_ordonez ya nada es igual que cuando las ...      sexist   
2297  @modadulce Estoy de acuerdo, me parece que ten...  non-sexist   
2873  #BCSinAdicciones| FAIMUDEl día de hoy realizam...  non-sexist   

                             task2  \
1374                    non-sexist   
2293                    non-sexist   
3379                    non-sexist   
1090                    non-sexist   
1803        ideological-inequality   
2694        ideological-inequality   
461                     non-sexist   
3346  misogyny-non-sexual-violence   
2297                    non-sexist   
2873                    non-sexist   

                                        text_anonymized  
1374  if i ever catch anyone beating a women, i swea...  
2293  "no sé si habrá un #hashtag del cine español. ...  
3379  en el dia de hoy se sostuvo reunión con claudi...  
1090  man i love a good podcast. i highly recommend ...  
1803  #hashtag#hashtag#hashtag not transgender!.#has...  
2694  tw/ transfobia "no es opresión" -hombres desle...  
461           @user maybe its repressed antiblackness .  
3346  @user ya nada es igual que cuando las putas y ...  
2297  @user estoy de acuerdo, me parece que tenemos ...  
2873  #hashtag| faimudel día de hoy realizamos una m...

In [ ]:
# Eliminar &text; etiquetas html

shuffled_train_data.text_anonymized = shuffled_train_data.text_anonymized.apply(lambda x: re.sub(r'&[a-zñ]+;', '', x))
shuffled_train_data.iloc[4000:4010]
shuffled_test_data.text_anonymized = shuffled_test_data.text_anonymized.apply(lambda x: re.sub(r'&[a-zñ]+;', '', x))
shuffled_test_data.iloc[4000:4010]

test_case     id   source language  \
4232  EXIST2021  11210  twitter       es   
116   EXIST2021   7094  twitter       en   
3545  EXIST2021  10523  twitter       es   
740   EXIST2021   7718      gab       en   
4199  EXIST2021  11177  twitter       es   
1974  EXIST2021   8952      gab       en   
1081  EXIST2021   8059  twitter       en   
3675  EXIST2021  10653      gab       es   
1810  EXIST2021   8788  twitter       en   
830   EXIST2021   7808      gab       en   

                                                   text       task1  \
4232  @DrManuelGarcia Jajaja de 100// 90 pero por de...      sexist   
116   @s00m3u get your fancam out of the tomasito ha...      sexist   
3545  @Luis_Delia Cuánta mierda y escoria kiechneris...  non-sexist   
740   Lying falase victim democrat agent Joy Villa w...      sexist   
4199  @HStylesSP @Harry_Styles Empoderamiento con es...  non-sexist   
1974  .......who do you think put that meme of #mans...      sexist   
1081  Isaias Afewerki &amp; @AbiyAhmedAli both lied ...  non-sexist   
3675               Coletas mandado callar a la feminazi      sexist   
1810  @YourQueenBri1 @BearsgetWATSON @teddy420180 @A...      sexist   
830   Yeah, here you come knockin' on my door, baby ...      sexist   

                             task2  \
4232        stereotyping-dominance   
116   misogyny-non-sexual-violence   
3545                    non-sexist   
740         ideological-inequality   
4199                    non-sexist   
1974  misogyny-non-sexual-violence   
1081                    non-sexist   
3675        ideological-inequality   
1810  misogyny-non-sexual-violence   
830                objectification   

                                        text_anonymized  
4232  @user jajaja de 100// 90 pero por desgracia si...  
116   @user get your fancam out of the tomasito hash...  
3545  @user cuánta mierda y escoria kiechnerista ......  
740   lying falase victim democrat agent joy villa w...  
4199  @user @user empoderamiento con esta cancioooon...  
1974  .......who do you think put that meme of #hash...  
1081  isaias afewerki  @user both lied about eritrea...  
3675               coletas mandado callar a la feminazi  
1810  @user @user @user @user since when was it okay...  
830   yeah, here you come knockin' on my door, baby ...

In [ ]:
# Eliminar caráctres especiales, #:)(/\='] usados en emojis y hashtags

shuffled_train_data.text_anonymized = shuffled_train_data.text_anonymized.str.replace("[^a-zA-ZñÑ]", " ")
shuffled_train_data.head(10)
shuffled_test_data.text_anonymized = shuffled_test_data.text_anonymized.str.replace("[^a-zA-ZñÑ]", " ")
shuffled_test_data.head(10)

<ipython-input-8-805ed98d7813>:3: FutureWarning: The default value of regex will change from True to False in a future version.
  shuffled_train_data.text_anonymized = shuffled_train_data.text_anonymized.str.replace("[^a-zA-ZñÑ]", " ")
<ipython-input-8-805ed98d7813>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  shuffled_test_data.text_anonymized = shuffled_test_data.text_anonymized.str.replace("[^a-zA-ZñÑ]", " ")


test_case     id   source language  \
1374  EXIST2021   8352  twitter       en   
2293  EXIST2021   9271  twitter       es   
3379  EXIST2021  10357  twitter       es   
1090  EXIST2021   8068  twitter       en   
1803  EXIST2021   8781  twitter       en   
2694  EXIST2021   9672  twitter       es   
461   EXIST2021   7439  twitter       en   
3346  EXIST2021  10324  twitter       es   
2297  EXIST2021   9275  twitter       es   
2873  EXIST2021   9851  twitter       es   

                                                   text       task1  \
1374  if i ever catch anyone beating a women, i swea...  non-sexist   
2293  "No sé si habrá un #MeToo del cine español. Cu...  non-sexist   
3379  En el dia de hoy se sostuvo reunión con Claudi...  non-sexist   
1090  Man I love a good podcast. I highly recommend ...  non-sexist   
1803  #BidenErasedWomen#BidenAintSmart#RealWomenMatt...      sexist   
2694  tw/ transfobia "no es opresión" -hombres desle...      sexist   
461    @not_corona_ maybe its repressed antiblackness .  non-sexist   
3346  @dara_ordonez ya nada es igual que cuando las ...      sexist   
2297  @modadulce Estoy de acuerdo, me parece que ten...  non-sexist   
2873  #BCSinAdicciones| FAIMUDEl día de hoy realizam...  non-sexist   

                             task2  \
1374                    non-sexist   
2293                    non-sexist   
3379                    non-sexist   
1090                    non-sexist   
1803        ideological-inequality   
2694        ideological-inequality   
461                     non-sexist   
3346  misogyny-non-sexual-violence   
2297                    non-sexist   
2873                    non-sexist   

                                        text_anonymized  
1374  if i ever catch anyone beating a women  i swea...  
2293   no s  si habr  un  hashtag del cine español  ...  
3379  en el dia de hoy se sostuvo reuni n con claudi...  
1090  man i love a good podcast  i highly recommend ...  
1803   hashtag hashtag hashtag not transgender   has...  
2694  tw  transfobia  no es opresi n   hombres desle...  
461            user maybe its repressed antiblackness    
3346   user ya nada es igual que cuando las putas y ...  
2297   user estoy de acuerdo  me parece que tenemos ...  
2873   hashtag  faimudel d a de hoy realizamos una m...

In [ ]:
# Eliminar la columna 'text'
shuffled_train_data.drop('text', axis=1, inplace=True)
shuffled_test_data.drop('text', axis=1, inplace=True)
# Renombrar la columna 'text_anonimized' como 'text'
shuffled_train_data.rename(columns={'text_anonymized': 'text'}, inplace=True)
#shuffled_train_data.iloc[4000:4010]
shuffled_test_data.rename(columns={'text_anonymized': 'text'}, inplace=True)
shuffled_test_data.head(10)

test_case     id   source language       task1  \
1374  EXIST2021   8352  twitter       en  non-sexist   
2293  EXIST2021   9271  twitter       es  non-sexist   
3379  EXIST2021  10357  twitter       es  non-sexist   
1090  EXIST2021   8068  twitter       en  non-sexist   
1803  EXIST2021   8781  twitter       en      sexist   
2694  EXIST2021   9672  twitter       es      sexist   
461   EXIST2021   7439  twitter       en  non-sexist   
3346  EXIST2021  10324  twitter       es      sexist   
2297  EXIST2021   9275  twitter       es  non-sexist   
2873  EXIST2021   9851  twitter       es  non-sexist   

                             task2  \
1374                    non-sexist   
2293                    non-sexist   
3379                    non-sexist   
1090                    non-sexist   
1803        ideological-inequality   
2694        ideological-inequality   
461                     non-sexist   
3346  misogyny-non-sexual-violence   
2297                    non-sexist   
2873                    non-sexist   

                                                   text  
1374  if i ever catch anyone beating a women  i swea...  
2293   no s  si habr  un  hashtag del cine español  ...  
3379  en el dia de hoy se sostuvo reuni n con claudi...  
1090  man i love a good podcast  i highly recommend ...  
1803   hashtag hashtag hashtag not transgender   has...  
2694  tw  transfobia  no es opresi n   hombres desle...  
461            user maybe its repressed antiblackness    
3346   user ya nada es igual que cuando las putas y ...  
2297   user estoy de acuerdo  me parece que tenemos ...  
2873   hashtag  faimudel d a de hoy realizamos una m...

In [ ]:
# Cargar el tokenizador de BERT
#tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased', vocab_size=30522)
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')


# Cargar el modelo BERT pre-entrenado
model = TFBertForSequenceClassification.from_pretrained('bert-base-multilingual-cased', num_labels=2)

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
MAX_LEN=255

In [ ]:
X = shuffled_train_data['text'].values
y = shuffled_train_data['task1'].values
Z = shuffled_test_data['text'].values
z = shuffled_test_data['task1'].values

In [ ]:
# Dividir los datos en entrenamiento y prueba
train_text, val_text, train_task1, val_task1 = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
import numpy as np
from transformers import BertTokenizer

def tokenize_bert(data, max_len=MAX_LEN):
    tokenizer_bert = BertTokenizer.from_pretrained('bert-base-multilingual-cased')
    input_ids = []
    attention_masks = []
    for i in range(len(data)):
        encoded = tokenizer_bert.encode_plus(
            data[i],
            add_special_tokens=True,
            max_length=max_len,
            padding='max_length',
            truncation=True,
            truncation_strategy='longest_first',
            return_attention_mask=True
        )
        input_ids.append(encoded['input_ids'])
        attention_masks.append(encoded['attention_mask'])
    return np.array(input_ids), np.array(attention_masks)

In [ ]:
#keras
import tensorflow as tf
from tensorflow import keras


#metrics
from sklearn.metrics import accuracy_score, f1_score
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
from sklearn import preprocessing
ohe = preprocessing.OneHotEncoder()
y_train = ohe.fit_transform(np.array(train_task1).reshape(-1, 1)).toarray()
y_valid = ohe.fit_transform(np.array(val_task1).reshape(-1, 1)).toarray()
z_test = ohe.fit_transform(np.array(z).reshape(-1, 1)).toarray()

In [ ]:
train_input_ids, train_attention_masks = tokenize_bert(train_text, MAX_LEN)
val_input_ids, val_attention_masks = tokenize_bert(val_text, MAX_LEN)
test_input_ids, test_attention_masks = tokenize_bert(Z, MAX_LEN)

In [ ]:
print(train_input_ids.shape)
print(val_input_ids.shape)
print(test_input_ids.shape)

(9581, 255)
(2396, 255)
(4368, 255)


In [ ]:
def create_model(bert_model, max_len=MAX_LEN):
    opt = tf.keras.optimizers.Adam(learning_rate=1e-5)
    loss = tf.keras.losses.BinaryCrossentropy()
    accuracy = tf.keras.metrics.BinaryAccuracy()

    input_ids = tf.keras.Input(shape=(max_len,), dtype='int32')
    attention_masks = tf.keras.Input(shape=(max_len,), dtype='int32')
    output = bert_model([input_ids, attention_masks])
    output = output[1]

    output = tf.keras.layers.BatchNormalization(momentum=0.9,
    epsilon=1e-5,
    center=True,
    scale=True,
    )(output)
    # Agregar Dropout
    output = tf.keras.layers.Dropout(0.5)(output)

    # Aumentar el tamaño de las capas ocultas
    #output = tf.keras.layers.Dense(256, activation='relu')(output)
    #output = tf.keras.layers.Dense(128, activation='relu')(output)

    output = tf.keras.layers.Dense(512, activation='relu')(output)
    output = tf.keras.layers.Dense(256, activation='relu')(output)
    output = tf.keras.layers.Dense(128, activation='relu')(output)

    output = tf.keras.layers.Dense(64, activation='relu')(output)

    #output = tf.keras.layers.Dense(2, activation='softmax')(output)

    output = tf.keras.layers.Dense(2, activation=tf.nn.softmax)(output)
    model = tf.keras.models.Model(inputs=[input_ids, attention_masks], outputs=output)

    # Compilar el modelo
    model.compile(opt, loss=loss, metrics=accuracy)

    # Agregar Early Stopping
    early_stopping = tf.keras.callbacks.EarlyStopping(patience=2, monitor='val_loss')

    return model, early_stopping

In [ ]:
bert_model = TFBertModel.from_pretrained('bert-base-multilingual-cased')


Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [ ]:
#model = create_model(roberta_model, MAX_LEN)
model, early_stopping = create_model(bert_model, MAX_LEN)
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 255)]        0           []                               
                                                                                                  
 input_2 (InputLayer)           [(None, 255)]        0           []                               
                                                                                                  
 tf_bert_model (TFBertModel)    TFBaseModelOutputWi  177853440   ['input_1[0][0]',                
                                thPoolingAndCrossAt               'input_2[0][0]']                
                                tentions(last_hidde                                               
                                n_state=(None, 255,                                           

In [ ]:
history = model.fit([train_input_ids,train_attention_masks], y_train, validation_data=([val_input_ids,val_attention_masks], y_valid), epochs=8, batch_size=32)

Epoch 1/8
300/300 [==============================] - 594s 2s/step - loss: 0.7288 - binary_accuracy: 0.5562 - val_loss: 0.5939 - val_binary_accuracy: 0.6653
Epoch 2/8
300/300 [==============================] - 567s 2s/step - loss: 0.5592 - binary_accuracy: 0.7212 - val_loss: 0.4938 - val_binary_accuracy: 0.7659
Epoch 3/8
300/300 [==============================] - 567s 2s/step - loss: 0.4377 - binary_accuracy: 0.8058 - val_loss: 0.4454 - val_binary_accuracy: 0.8034
Epoch 4/8
300/300 [==============================] - 567s 2s/step - loss: 0.3312 - binary_accuracy: 0.8622 - val_loss: 0.4111 - val_binary_accuracy: 0.8427
Epoch 5/8
300/300 [==============================] - 567s 2s/step - loss: 0.2286 - binary_accuracy: 0.9128 - val_loss: 0.3949 - val_binary_accuracy: 0.8497
Epoch 6/8
300/300 [==============================] - 567s 2s/step - loss: 0.1642 - binary_accuracy: 0.9369 - val_loss: 0.4615 - val_binary_accuracy: 0.8560
Epoch 7/8
300/300 [==============================] - 528s 2s/ste

In [ ]:
result_bert = model.predict([test_input_ids,test_attention_masks])

137/137 [==============================] - 85s 584ms/step


In [ ]:
y_pred_bert =  np.zeros_like(result_bert)
y_pred_bert[np.arange(len(y_pred_bert)), result_bert.argmax(1)] = 1

In [ ]:
print('\tClassification Report for BERT:\n\n',classification_report(z_test,y_pred_bert, target_names=['sexist', 'non-sexist']))


	Classification Report for BERT:

               precision    recall  f1-score   support

      sexist       0.77      0.59      0.67      2087
  non-sexist       0.69      0.84      0.76      2281

   micro avg       0.72      0.72      0.72      4368
   macro avg       0.73      0.71      0.71      4368
weighted avg       0.73      0.72      0.71      4368
 samples avg       0.72      0.72      0.72      4368



# **Swapping + ampliando red profunda.**

Resultados 11_8_23  Train :
```
 Epoch 1/8
300/300 [==============================] - 594s 2s/step - loss: 0.7288 - binary_accuracy: 0.5562 - val_loss: 0.5939 - val_binary_accuracy: 0.6653
Epoch 2/8
300/300 [==============================] - 567s 2s/step - loss: 0.5592 - binary_accuracy: 0.7212 - val_loss: 0.4938 - val_binary_accuracy: 0.7659
Epoch 3/8
300/300 [==============================] - 567s 2s/step - loss: 0.4377 - binary_accuracy: 0.8058 - val_loss: 0.4454 - val_binary_accuracy: 0.8034
Epoch 4/8
300/300 [==============================] - 567s 2s/step - loss: 0.3312 - binary_accuracy: 0.8622 - val_loss: 0.4111 - val_binary_accuracy: 0.8427
Epoch 5/8
300/300 [==============================] - 567s 2s/step - loss: 0.2286 - binary_accuracy: 0.9128 - val_loss: 0.3949 - val_binary_accuracy: 0.8497
Epoch 6/8
300/300 [==============================] - 567s 2s/step - loss: 0.1642 - binary_accuracy: 0.9369 - val_loss: 0.4615 - val_binary_accuracy: 0.8560
Epoch 7/8
300/300 [==============================] - 528s 2s/step - loss: 0.1142 - binary_accuracy: 0.9573 - val_loss: 0.4060 - val_binary_accuracy: 0.8823
Epoch 8/8
300/300 [==============================] - 528s 2s/step - loss: 0.0787 - binary_accuracy: 0.9721 - val_loss: 0.5649 - val_binary_accuracy: 0.8598

Evaluación:


```

```

Classification Report for BERT:

               precision    recall  f1-score   support

      sexist       0.77      0.59      0.67      2087
  non-sexist       0.69      0.84      0.76      2281

   micro avg       0.72      0.72      0.72      4368
   macro avg       0.73      0.71      0.71      4368
weighted avg       0.73      0.72      0.71      4368
 samples avg       0.72      0.72      0.72      4368

No mejora los resultados para epochs = 6 y con menos capas. Es muy similar.

Classification Report for BERT:

               precision    recall  f1-score   support

      sexist       0.70      0.76      0.73      2087
  non-sexist       0.76      0.70      0.73      2281

   micro avg       0.73      0.73      0.73      4368
   macro avg       0.73      0.73      0.73      4368
weighted avg       0.73      0.73      0.73      4368
 samples avg       0.73      0.73      0.73      4368

```

